#!/usr/bin/env tsx

function main() {
  console.log('\n' + '═'.repeat(70));
  console.log('  Context Curator - Help');
  console.log('═'.repeat(70));
  console.log('');
  console.log('A tool for managing Claude Code session context.');
  console.log('');
  console.log('SESSION TYPES:');
  console.log('');
  console.log('  Named Sessions');
  console.log('  - Stored in ~/.claude/sessions/<session-id>/');
  console.log('  - Globally accessible by name');
  console.log('  - Resume with: claude -r <name>');
  console.log('  - Examples: context-curator, my-workflow');
  console.log('');
  console.log('  Unnamed Sessions');
  console.log('  - Stored in ~/.claude/projects/<project-dir>/<uuid>.jsonl');
  console.log('  - Project-specific (scoped by directory)');
  console.log('  - Automatically created by Claude Code');
  console.log('  - Example: 8e14f625-bd1a-4e79-a382-2d6c0649df97');
  console.log('');
  console.log('PROJECT DIRECTORY FORMULA:');
  console.log('');
  console.log('  /Users/dev/my-project  →  -Users-dev-my-project');
  console.log('  /home/user/work/app    →  -home-user-work-app');
  console.log('');
  console.log('  Formula: projectDir = fullPath.replace(/\\//g, \'-\')');
  console.log('');
  console.log('COMMANDS:');
  console.log('');
  console.log('  show sessions');
  console.log('    List all sessions (named + unnamed for current project)');
  console.log('    Usage: npm --prefix ~/.claude/skills/context-curator run show');
  console.log('');
  console.log('  summarize <session-id>');
  console.log('    Analyze a session and show token breakdown');
  console.log('    Usage: npm --prefix ~/.claude/skills/context-curator run summarize <id>');
  console.log('');
  console.log('  checkpoint <session-id> <new-name>');
  console.log('    Create a backup/fork of a session as a named session');
  console.log('    Usage: npm --prefix ~/.claude/skills/context-curator run checkpoint <id> <name>');
  console.log('');
  console.log('  delete <session-id>');
  console.log('    Remove a session (creates backup first)');
  console.log('    Usage: npm --prefix ~/.claude/skills/context-curator run delete <id>');
  console.log('');
  console.log('  dump <session-id>');
  console.log('    View raw JSONL contents of a session');
  console.log('    Usage: npm --prefix ~/.claude/skills/context-curator run dump <id>');
  console.log('');
  console.log('  help');
  console.log('    Show this help message');
  console.log('    Usage: npm --prefix ~/.claude/skills/context-curator run help');
  console.log('');
  console.log('INSTALLATION:');
  console.log('');
  console.log('  git clone <repo> ~/.claude/skills/context-curator');
  console.log('  cd ~/.claude/skills/context-curator');
  console.log('  npm install');
  console.log('  ./setup.sh');
  console.log('');
  console.log('USAGE:');
  console.log('');
  console.log('  cd ~/any-project');
  console.log('  claude -r context-curator');
  console.log('');
  console.log('═'.repeat(70));
  console.log('');
}

main();
